/* Generated by Copilot -- Tweaked by bathtaters */
export default function BotIcon({
  className = "w-8 h-auto",
}: {
  className?: string;
}) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 60 60"
      className={`fill-current stroke-current ${className}`}
    >
      <rect
        x="5"
        y="15"
        width="50"
        height="40"
        rx="10"
        ry="10"
        className="stroke-2 fill-none"
      />
      <circle cx="15" cy="35" r="5" className="stroke-none" />
      <circle cx="45" cy="35" r="5" className="stroke-none" />
      <rect x="25" y="45" width="10" height="5" className="stroke-none" />
      <rect x="27.5" y="5" width="5" height="10" className="stroke-none" />
      {/* <rect x="20" y="5" width="5" height="10" className="stroke-none" /> */}
      {/* <rect x="35" y="5" width="5" height="10" className="stroke-none" /> */}
    </svg>
  );
}
