name: Deploy to Production

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod
  workflow_dispatch:

jobs:
  deploy-prod:
    name: run deploy w/ prod vars
    uses: ./.github/workflows/deploy.yml
    with:
      name: "mtg-drafter"
      environment: "mtg-drafter-prod"