name: Deploy to Test Server

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    name: run deploy w/ test vars
    uses: ./.github/workflows/deploy.yml
    with:
      name: "mtg-drafter-test"
      environment: "mtg-drafter-test"