# !! This workflow requires podman & rsync installed on the remote host !! #

name: Deploy to Production

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main
      
      - name: Install Node.js
        uses: actions/setup-node@main
        with:
          node-version-file: '.nvmrc'
      
      - name: Install Podman
        run: |
          if ! command -v podman &> /dev/null; then
            sudo apt-get install -y podman
          fi
      
      - name: Generate package-lock
        run: npm i --package-lock-only

      - name: Copy .env
        run: echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' > .env.prod
      
      - name: Fix for podman cache
        # Fixes permissions error during cleanup
        run: |
          sudo mv -fv /usr/bin/tar /usr/bin/tar.orig
          echo -e '#!/bin/sh\n\nsudo /usr/bin/tar.orig "$@"' | sudo tee -a /usr/bin/tar
          sudo chmod +x /usr/bin/tar

      - name: Cache podman-machine
        uses: actions/cache@main
        with:
          path: |
            ~/.local/share/containers
            ~/.config/containers
          key: ${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('package.json') }}
  
      - name: Build image
        run: podman build -t mtg-drafter .

      - name: Compress image
        run: podman save -o mtg-drafter.tar mtg-drafter

      - name: Upload image
        uses: actions/upload-artifact@main
        with:
          name: mtgd-image
          path: mtg-drafter.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download image
        uses: actions/download-artifact@main
        with:
          name: mtgd-image
          path: .
      
      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.REMOTE_HOST }} > ~/.ssh/known_hosts

      - name: Copy image to host
        run: rsync -cvz mtg-drafter.tar ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }}:${{ vars.REMOTE_TARGET }}/
        
      - name: Remove old container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }} << 'EOF'
          cd ${{ vars.REMOTE_TARGET }}
          podman stop -i mtg-drafter
          podman rm -i mtg-drafter
          podman rmi -i mtg-drafter
          EOF
      
      - name: Deploy new container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }} << 'EOF'
          cd ${{ vars.REMOTE_TARGET }}
          podman load -i mtg-drafter.tar
          podman run -d --name mtg-drafter -p 3040:3040 mtg-drafter
          EOF
