# !! This workflow requires both podman & rsync are install on the remote host. !! #

name: Deploy to Production

on:
  push:
    branches:
      - test-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main
      
      - name: Install Node.js
        uses: actions/setup-node@main
        with:
          node-version-file: '.nvmrc'
      
      - name: Install Podman if not already installed
        run: |
          if ! command -v podman &> /dev/null; then
            sudo apt-get install -y podman
          fi
      
      - name: Generate package-lock
        run: npm i --package-lock-only

      - name: Copy .env
        run: echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' > .env.prod

      - name: Build image
        run: podman build -t mtg-drafter .

      - name: Compress image
        run: podman save -o mtg-drafter.tar mtg-drafter

      - name: Upload image
        uses: actions/upload-artifact@main
        with:
          name: mtgd-image
          path: mtg-drafter.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download image
        uses: actions/download-artifact@main
        with:
          name: mtgd-image
          path: mtg-drafter.tar
      
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-avzc -i"
            SOURCE: "mtg-drafter.tar"
            REMOTE_HOST: ${{ vars.REMOTE_HOST }}
            REMOTE_USER: ${{ vars.REMOTE_USER }}
            TARGET: ${{ vars.REMOTE_TARGET }}/
            SCRIPT_AFTER: |
              podman stop mtg-drafter || true
              podman rm -i mtg-drafter
              podman rmi -i mtg-drafter
              podman load -i mtg-drafter.tar
              podman run -d --name mtg-drafter -p 3041:3040 mtg-drafter
